name: RapSheetPlus
main: com.nuclearw.rapsheet.Rapsheet
version: ${project.version}
author: NuclearW and Quark
description: Rapsheet lets you charge players of crimes, and then look them up later. Plus version by Quark.
database: true
commands:
    rapsheet:
        description: Rapsheet command. Run for help.
        aliases: rap
        usage: |
            /<command>
permissions:
    rapsheet.*:
        description: Gives access to all Rapsheet commands
        children:
            rapsheet.lookup: true
            rapsheet.charge: true
            rapsheet.convict: true
            rapsheet.pardon: true
            rapsheet.seal: true
            rapsheet.viewsealed: true
            rapsheet.expunge: true
            rapsheet.lookupme: true
    rapsheet.lookup:
        description: Allows you to do a lookup
        default: op
    rapsheet.charge:
        description: Allows you to charge a player
        default: op
    rapsheet.lookupme:
        description: Allows you to lookup yourself, and only yourself.
        default: true
    rapsheet.convict:
        description: Allows you to convict a player
        default: op
    rapsheet.pardon:
        description: Allows you to pardon a player
        default: op
    rapsheet.seal:
        description: Allows you to seal a record
        default: op
    rapsheet.viewsealed:
        description: Allows you to view sealed records
        default: op
    rapsheet.expunge:
        description: Allows you to expunge a record
        default: op